"""empty message

Revision ID: cbde5c811dfc
Revises: c922e9bb711e
Create Date: 2021-01-30 10:40:05.820816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbde5c811dfc'
down_revision = 'c922e9bb711e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_times', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_times')
    # ### end Alembic commands ###
